apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: convert-to-dpfm-invoice-document-from-sap-billing-document
  name: convert-to-dpfm-invoice-document-from-sap-billing-document
spec:
  replicas: 1
  selector:
    matchLabels:
      run: convert-to-dpfm-invoice-document-from-sap-billing-document
      app: invoice-document
  template:
    metadata:
      labels:
        run: convert-to-dpfm-invoice-document-from-sap-billing-document
        app: invoice-document
    spec:
      hostname: convert-to-dpfm-invoice-document-from-sap-billing-document
      containers:
        - name: convert-to-dpfm-invoice-document-from-sap-billing-document
          image: latonaio/convert-to-dpfm-invoice-document-from-sap-billing-document
          imagePullPolicy: Always
          env:
            - name: "RMQ_QUEUE_FROM"
              value: "data-platform-api-invoice-document-creates-queue-from"
            - name: "RMQ_QUEUE_TO_SQL"
              value: "sql-update-kube"
            - name: "RMQ_QUEUE_TO_EX_CONF"
              value: ""
            - name: "RMQ_QUEUE_TO_HEADERS_SUB_FUNC"
              value: ""
            - name: "RMQ_QUEUE_TO_ITEMS_SUB_FUNC"
              value: ""
            - name: "RMQ_SESSION_CONTROL_QUEUE"
              value: "data-platform-api-invoice-document-creates-session-control-queue"
            - name: "DB_NAME"
              value: "DataPlatformMastersAndTransactionsMysqlKube"
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: convert-to-dpfm-invoice-document-from-sap-billing-document
  name: convert-to-dpfm-invoice-document-from-sap-billing-document
spec:
  selector:
    run: convert-to-dpfm-invoice-document-from-sap-billing-document
  type: NodePort
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30748
